### ISSUE TITLE
Class for images to scale them to 80% of their original size

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-docs#11]
Reasoning: We've got huge number of screenshots and resizing them manually is a pain. It'd be hard to automate this because we want to scale only some of them - basically those big ones that contain entire editor.

We can't just set max-width for them because they have various widths, so the scale ratio will be different what will look bad - 90%, 92%, 85%, etc... Ugly.

So if it's possible a class should be proposed which applied to img will scale it to let's say 80% of original size. We can assume that width&height attrs are set, but perfect solution should not assume that.

**Comment by wwalc** [comment]
Workaround using `<div class="responsive">`:

```
<div class="responsive">
{@img editor1.png Article Editor}
</div>
```
