### ISSUE TITLE
Guides menu – shouldn't it be collapsed?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-docs#124]
The amount of content here is overwhelming:

![image](https://user-images.githubusercontent.com/156149/35162018-36d6705e-fd42-11e7-88a5-b65d281381ae.png)

I'd propose folding categories from 3rd level down.

**Comment by AnnaTomanek** [comment]
To be resolved in https://github.com/cksource/umberto/issues/474 as it's an Umberto issue.
