### ISSUE TITLE
issue in the documentation

### ISSUE THREAD

**Issue by mohamed-jebri** [ckeditor/ckeditor-docs#128]
in the page [https://docs.ckeditor.com/ckeditor4/latest/guide/dev_installation.html](url)

a </ textarea> tag is misplaced in the <script> tag

` <script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace( 'editor1' );
            </textarea></script>`

**Comment by AnnaTomanek** [comment]
Hi Mohamed,

Thanks for spotting this. [It has already been fixed](https://github.com/ckeditor/ckeditor-docs/commit/02dd55a87a3b417710ac5807d30fffbfbe54d053) in the source, and will be published online soon.
