### ISSUE TITLE
API members (config, events) contributed by a plugin should explicitly mention the dependency

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-docs#138]
There are several cases where given API member (be it config, event, method etc) is contributed by a plugin.

For instance:
* [`config.pasteFromWordCleanupFile`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFromWordCleanupFile) is contributed by the `pastefromword` plugin.
* [`config.pasteFilter`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter) is contributed by the `clipboard` plugin.
* [`editor.change`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#event-change) event is contributed by the `undo` plugin.
* [`editor.addButton`](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_ui.html#method-addButton) method is contributed by the `button` plugin.

The way I see it is just to append an information like: contributed by xyz plugin

Where xyz is a name of the plugin linked to the addons repo. Also "plugin" is optional in case it doesn't fit well in terms of design.

This idea came after community feedback in https://github.com/ckeditor/ckeditor-dev/issues/984#issuecomment-365487842

**Comment by f1ames** [comment]
Just one think, I suppose we should clearly state what `contributed by xyz plugin` means (in this case it means that the property is not available without plugin) - so somebody reading the docs would know what such it means and how/when the property can be used.

**Comment by mlewand** [comment]
@f1ames do you think that "contributed by xyz plugin" does not state that clearly enough? Eventually we could put some sort of "i" (for info) icon next to it that as hovered/touched shows a more verbose description.

The question is whether this is really needed in that case.

**Comment by f1ames** [comment]
TBH I'm not sure really, "contributed by xyz plugin" states that "xyz" property was added by this plugin - and that's basically it. The part that without the plugin, "xyz" is not available is an assumption (very logical and straigtforward I suppose) based on that message.

Still, "contributed by xyz plugin" is short and concise (which is good) so we may go with it and check how it works.

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2906.
