### ISSUE TITLE
Link to contact us section regarding Spell Checker license

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-docs#146]
The documentation points to https://ckeditor.com/ckeditor-4/pricing/#spellCheck to purchase a license, which is a bit misleading as one may not notice that commercial license for spellchecker is **not** included in the default CKEditor package.

![screen shot 2018-03-22 at 17 25 13](https://user-images.githubusercontent.com/545175/37783617-3caa2004-2df6-11e8-8929-6e40529790e7.png)

We should link straight to the contact form.

**Comment by AnnaTomanek** [comment]
Fixed with https://github.com/ckeditor/ckeditor-docs/commit/b10691165aabb36e977c37a129d935d33be1e5ae.
