### ISSUE TITLE
Output format guid has inline styles

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-docs#163]
Output format (`dev/features/output_format`) guide has created list with HTML code, which contains inline styles, which breaks list items structure.
* https://docs.ckeditor.com/ckeditor4/latest/guide/dev_output_format.html#adjusting-output-formatting-through-configuration
* https://github.com/ckeditor/ckeditor-docs/blame/877ce1e892eeadb394726cbadc323c9ecda0433c/docs/guide/dev/features/output_format/README.md#L93-L119

**Comment by mlewand** [comment]
Fixed with #164.
