### ISSUE TITLE
Skin SDK guides are outdated

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor-docs#169]
Many of guides connected to skin SDK should be updated:

* [Introduction](https://docs.ckeditor.com/ckeditor4/latest/guide/skin_sdk_intro.html) states that the official skin is Moono, which is no longer true (the new one is Moono Lisa);
* [Bringing Your Skin to Life](https://docs.ckeditor.com/ckeditor4/latest/guide/skin_sdk_customize.html) links to Opera Dragonfly and Firebug, which are dead for years;
* nearly every guide in skin SDK section links to Moono for examples.

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2902.
