### ISSUE TITLE
Update code listings with markdown code block syntax

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-docs#175]
A lot of our code listing are indented by tabs. However, they are not always correctly recognized by our docs builder. We could improve docs UX by wrapping code listings with proper markdown code blocks. Also, some of the listing good be improved by correct indentation, mostly `HTML` samples.

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2900.
