### ISSUE TITLE
Uploading images is hard

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-docs#178]
I've been browsing the documentation for image upload and landed here:

https://docs.ckeditor.com/ckeditor4/latest/guide/dev_howtos_file_upload.html

That guide links to https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_upload.html so I went there.

The next guide is about client-server communication and I think it doesn't mention how to easily enable image upload... But it links to https://docs.ckeditor.com/ckeditor4/latest/guide/dev_drop_paste.html

So I went there. It didn't help me too. It has a broken video (404), talks about filtering the content and about many other things.

In none of these places did I find a mention of Easy Image and a quick guide on how to enable it. In fact, I still don't know. I've been lazy and didn't read those guides precisely, just searched for the right headers and links. I think that's quite accurate with how people search for information.

cc @AnnaTomanek

**Comment by AnnaTomanek** [comment]
All valid points. We did not make any adjustments when Easy Image was introduced, and we should have.

Curious: why did you skip the https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_browse_upload.html link that is listed there twice?

**Comment by Reinmar** [comment]
Cause I didn't look for a file manager but a simple drop-and-upload behaviour. Ofc, I know what our "file manager" is and that we also offer Easy Image, so I wasn't like a real user here. But I also think that "file manager" may not be attractive for people who look for quick and easy solutions. File manager sounds too serious.

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2897.
