### ISSUE TITLE
Add editor-plugin-conflict error code reference

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor-docs#179]
Some plugins e.g. `image`, `image2` and `easyimage` may be in conflict - in that case, one is more preferred than the other.

Additional data:
`plugin` - plugin causing conflict.
`replacedWith` - preferred plugin

See https://github.com/ckeditor/ckeditor-dev/pull/2246 for more details.

**Comment by jizhidexiaohuang** [comment]
![image](https://user-images.githubusercontent.com/29673251/57187891-873fef80-6f28-11e9-8277-5bc37d8c3c45.png)

**Comment by jizhidexiaohuang** [comment]
![image](https://user-images.githubusercontent.com/29673251/57187908-a2aafa80-6f28-11e9-9443-8f6d2a0b3d62.png)

**Comment by Pointotech** [comment]
Nothing in the linked documentation gives any hint at how to fix this warning.

**Comment by jacekbogdanski** [comment]
@Pointotech do you see any possible improvements in code error description available at - https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#editor-plugin-conflict ?

From my point of view the description:
![image](https://user-images.githubusercontent.com/10279586/109772472-51402500-7bfe-11eb-9d9c-941986db3305.png)

Is pretty explaining what's happening - the plugins are in conflict and `plugin: xxx` is replaced with `replacedWith: yyy`, so removing one plugin or another will fix the warning. In most cases, the plugin gets replaced by a more advanced feature.

**Comment by alexrodb** [comment]
[CKEDITOR] Error code: editor-plugin-conflict. {plugin: "image", replacedWith: "image2"

To remove this conflict, you can disable the loading of the plugin that you are not going to use or load as for example:
config.removePlugins = 'image';

This way "image2" is used and "image" is not used, the alert disappears in the javascript.

https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removePlugins
