### ISSUE TITLE
Source code editing should mention ACF

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-docs#188]
https://sdk.ckeditor.com/samples/sourcearea.html & https://ckeditor.com/docs/ckeditor4/latest/guide/dev_sourcearea.html

Right now it focuses on the feature itself (being able to modify the source code) while the real functionality heavily depends on ACF configuration (which changes in the source code will get rejected, which will not).

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2895.
