### ISSUE TITLE
Follow up task after merging Examples to docs building process

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-docs#200]
* After merge of sdk-port, there should be replaced names with SDK to names with Examples.
* Replace `linksdk` with `linkexample` in umberto's links.

mentioned in 'follow-up' section in 
https://github.com/ckeditor/ckeditor-docs/pull/184#pullrequestreview-178797034

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2892.
