### ISSUE TITLE
Broken rendering in drag and drop example

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-docs#209]
1. Open https://ckeditor.com/docs/ckeditor4/latest/examples/draganddrop.html
2. Drag and drop an item into the title.
3. The dropped placeholder is ugly:

![image](https://user-images.githubusercontent.com/156149/50969651-741f9480-14df-11e9-9abd-9897c3214a0f.png)

**Comment by f1ames** [comment]
Seems to have been fixed already (tested on CHrome and IE11). Closing.
