### ISSUE TITLE
Add option to change issueUrl and contributingUrl for sdk samples

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor-docs#220]
Integration SDK samples have different repos for reporting issues/contributing. We should allow to set different `issueUrl` and `contributingUrl` for them.

Within this change it be nice to add proper link in: `docs/sdk/examples/react.html`:
https://github.com/ckeditor/ckeditor4-react/issues/new

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2888.
