### ISSUE TITLE
Drop submodules of scayt and wsc directly in docs

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor-docs#224]
In a similar way as it was done #211, it could be possible to remove direct dependency of scayt and wsc plugins.
Those plugins exists inside presets and it supposed to keep them sync.
Right now docs are taken directly from submodules inside ckeditor-docs, where build packages used in examples use version inside ckeditor-presets.

It seems like we could drop this dependency and update only those links:
https://github.com/ckeditor/ckeditor-docs/blob/d4d0580f39d7d228a069c0474799f91f5d930591/gruntfile.js#L84-L85

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2886.
