### ISSUE TITLE
Deprecate grunt docs in favor of grunt build task

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-docs#231]
I've been doing countless mistakes of typing `grunt build` instead of `grunt docs`. This results with error message delayed by second or few secs.

`build` task name seems much more intuitive for me, and has always been. Though I'm curious to get opinions from other people familiar with doc generation process.

The way I propose it is to:
1. Rename `docs` task to `build`
1. Add `docs` alias which will add a message that `grunt docs` is deprecated and will be removed in couple of months - use `grunt build` instead.

After a longer time we'd drop the old command.

**Comment by engineering-this** [comment]
I fully agree 👍

**Comment by msamsel** [comment]
@mlewand I think it might be combined with this PR:
https://github.com/ckeditor/ckeditor-docs/pull/206

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2884.
