### ISSUE TITLE
How to get cursor pointer to a ckeditor on basis of id provided to a ckeditor

### ISSUE THREAD

**Issue by Neha7777** [ckeditor/ckeditor-docs#241]
All issues regarding CKEditor 4 Documentation should be reported in the `ckeditor-dev` repository - https://github.com/ckeditor/ckeditor-dev/issues/new/choose.

Any issues reported here will be moved to the `ckeditor-dev` repository.

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
