### ISSUE TITLE
Ck Editor initialize issue in angular while page initializing second time after saving

### ISSUE THREAD

**Issue by antonyvimal** [ckeditor/ckeditor-docs#253]
I am using the CK Editor in my angular project, it is getting loaded properly for the first page initialized. For the second time control is not getting rendered properly also am getting the error message. Thanks in advance.

I have tried to re-initialized for the second time, but that is not working. I have mentioned the error message received from the screen for your reference.

Uncaught TypeError: Cannot read property 'getSelection' of undefined

**Comment by f1ames** [comment]
Hello @antonyvimal,
this is CKEditor 4 documentation repository. To report any issue regarding CKEditor 4 Angular integration please create new issue in [`ckeditor4-angular` repository](https://github.com/ckeditor/ckeditor4-angular/issues/new). Please, remember about providing reproduction steps so we can reproduce the issue.

**Comment by antonyvimal** [comment]
> Hello @antonyvimal,
> this is CKEditor 4 documentation repository. To report any issue regarding CKEditor 4 Angular integration please create new issue in [`ckeditor4-angular` repository](https://github.com/ckeditor/ckeditor4-angular/issues/new). Please, remember about providing reproduction steps so we can reproduce the issue.

**Comment by antonyvimal** [comment]
> Hello @antonyvimal,
> this is CKEditor 4 documentation repository. To report any issue regarding CKEditor 4 Angular integration please create new issue in [`ckeditor4-angular` repository](https://github.com/ckeditor/ckeditor4-angular/issues/new). Please, remember about providing reproduction steps so we can reproduce the issue.

Thank you...
