### ISSUE TITLE
Give life to docs - comments and/or on-page feedback form

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-docs#29]
Our docs are like a book now. They are immutable and hardly commentable. Theoretically one can report us a problem, but he needs to find this repository, register to GH and explain what's wrong and where. In result we have very little feedback. For instance, #27 existed for a long time and would exist even longer if we weren't checking SO.
## Proposed solution - feedback form

We can use some existing system that allows to easily report issues or give other kind of feedback. I imagine that we can have a link on every page to such system or, if the system we chose supports that, an expandable form that sends its content to that online system.

Requirements:
- It should work in the downloaded version of documentation.
- We must know on which page the user was when sending a comment.
## More life

Alternatively or in addition to the feedback form, we can make articles commentable. I think that using for example Discuss we could rather easily make all articles commentable. Why would I try this? I'm curious if users of our documentation will post something valuable for other users. Perhaps not, because we are not PHP and most developers know very little about CKEditor, but still this may be an interesting to see.

To avoid FUD I think that comments should go through moderation and that we should warn users that only certain types of comments will appear on the page.

Additionally, I thought about SEO which comments could improve, but I don't think that solution based on [Disqus](http://disqus.com) will be read by Google bots.

**Comment by f1ames** [comment]
Closing this issue as there is ongoing process to add some feedback widget to the entire docs ecosystem which will cover this issue.
