### ISSUE TITLE
Guide about contents.css and matching final page's styling

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-docs#37]
Should be linked in:
- http://docs.ckeditor.com/#!/guide/dev_framed
- http://docs.ckeditor.com/#!/guide/dev_best_practices-section-configuration
- http://docs.ckeditor.com/#!/guide/dev_styles

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2917.
