### ISSUE TITLE
Write a tutorial about creating skins

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-docs#42]
We have already a draft of such documentation article created by Sebastian. Adding this to the documentation will help in fixing https://github.com/ckeditor/ckeditor-skintuner/issues/5

**Comment by f1ames** [comment]
We have some docs about creating skins already https://ckeditor.com/docs/ckeditor4/latest/guide/skin_sdk_setup.html. Since this topic wasn't touched for such a long time I think there is no sense in keeping this issue open.
