### ISSUE TITLE
Revise docs.ckeditor.com landing page

### ISSUE THREAD

**Issue by AnnaTomanek** [ckeditor/ckeditor-docs#45]
The text is outdated, some fragments make no sense.

It also looks really ugly, the badly aligned right column is an eyesore.

We should also add a prominent link to the CKEditor SDK there.

**Comment by AnnaTomanek** [comment]
Partly fixed (content-wise) with https://github.com/ckeditor/ckeditor-docs/commit/a491656b0ec94c20e1c4ff133a05d34d62f17a7a.

Layout... is not a priority at the moment.

**Comment by oleq** [comment]
> @oleq, any ideas on better placement of the stuff on the landing page?

No :sweat_smile:
