### ISSUE TITLE
Use Grunt

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor-docs#46]
There's [grunt-jsduck](https://github.com/dpashkevich/grunt-jsduck) task. Combining it with [grunt-contrib-copy](https://github.com/gruntjs/grunt-contrib-copy) will give us everything we need to replace our nasty old bash script.

**Comment by oleq** [comment]
Migration to Grunt in https://github.com/ckeditor/ckeditor-docs/tree/t/46. Mostly because working on #47 drives me crazy with `build.sh`.

1. Created `jsduck` multi task. Couldn't use https://github.com/dpashkevich/grunt-jsduck because it hardcodes the name of the command to execute (`jsduck` while we use `ckeditor-jsduck` or `ckfinder-jsduck`). Besides, it is quite old and unmaintained.
2. Used `grunt copy` task to apply customisations.
3. Removed old `build.sh` and updated documentation.

Things to check:
1. `package.json`: is the license right? Is the version right?
2. Overall performance: is the build OK? Is there anything missing?

**Comment by AnnaTomanek** [comment]
As a professional developer here, I tested it on Windows and it works :D The documentation was built, it took a while, but it's comparable to old `build.sh`, I guess.

As for the license, I doubt we need the http://ckeditor.com/license part. If anything, rather this one: http://docs.ckeditor.com/LICENSE.html?

**Comment by Reinmar** [comment]
Merged to master with ab1ef61.

In the `package.json` I linked to `LICENSE.md` only. http://docs.ckeditor.com/LICENSE.html is more for a distribution. Hopefully @wwalc agrees :D.
