### ISSUE TITLE
HOWTOs article about jQuery UI dialogs and Bootstrap modals compatibility

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-docs#52]
Proposed content:

https://gist.github.com/Reinmar/b9df3f30a05786511a42

I'll also attached files that I used for testing if anyone will need to get back to this.

When we'll add the article, we should post links to it in all threads that may be often visited.

**Comment by Reinmar** [comment]
* https://gist.github.com/Reinmar/b9116e6d21d88b2d0d40
* https://gist.github.com/Reinmar/1958b6012034db84cc0b

**Comment by jswiderski** [comment]
I approve this article:) Very well written + there are code examples.
Even beginner should understand it.

**Comment by Reinmar** [comment]
DUP http://dev.ckeditor.com/ticket/12768

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2914.
