### ISSUE TITLE
There is no information that about half of events which are fired on editor requires plugins

### ISSUE THREAD

**Issue by adelura** [ckeditor/ckeditor-docs#53]
For example there is no information that `undo` plugin is required to fire change `event`.
http://docs.ckeditor.com/#!/api/CKEDITOR.editor-event-change

I might be annoying for people who want to have event to be fired but nothing happens.

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2913.
