### ISSUE TITLE
Article about listening on DOM events in CKEditor

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-docs#55]
https://gist.github.com/Reinmar/9665f1630cd6287b4c2b + more info about `editable.attachListener()` and why not to listen to events on elements inside the editable.

**Comment by adelura** [comment]
> a series of CKEditor events is fired on parent objects.

a series of CKEditor events is fired on ~~parent~~ ascendant objects.

----

Code snippet syntax is not highlighted.

----

I would also add an information about diffrences between `on` and `attachListener`.

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2912.
