### ISSUE TITLE
Confusing information about CKFinder integration for Image Upload

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor-docs#59]
[CKEditor docs](http://docs.ckeditor.com/#!/guide/dev_file_upload) mentions that it [might be used with CKFinder](http://docs.ckeditor.com/#!/guide/dev_file_upload-section-using-with-ckfinder).

The problem is that users will [try to use it with CKFinder 2.x](http://stackoverflow.com/questions/31415088/getting-wrong-responses-from-ckfinder-when-inserting-images-via-drag-and-drop/31422581#31422581) for some reason ;)

Please add info that this will work only with CKFinder 3.0+.

**Comment by jodator** [comment]
Not a bug. I didn't notice that someone updated CKFinder 2.x with this changes.
Anyway it should be noted that this thing will work only with CKFinder 2.5.x+ and CKFinder 3.0.

**Comment by AnnaTomanek** [comment]
Fixed with https://github.com/ckeditor/ckeditor-docs/commit/70bf5cb5c80d1089659e050fbf16d5ca18a80f2a.
