### ISSUE TITLE
change default text color

### ISSUE THREAD

**Issue by atiertant** [ckeditor/ckeditor-docs#68]
how could i change default text color?

    colorButton_foreStyle: {
      element: 'font',
      attributes: { 'color': '#FF0000' }
    }

doesn't work....

**Comment by f1ames** [comment]
Hi @atiertant,
this is the place to report issues related to CKEditor 4 docs not CKEditor 4 questions.

I believe the best places to look for the answer to your question may be CKEditor 4 [docs](http://docs.ckeditor.com/) and [sdk](http://sdk.ckeditor.com). You may also look on stackoverflow, it seems there is already an [answer](http://stackoverflow.com/questions/15561270/how-to-config-text-default-color-in-ckeditor/15564887#15564887) to your question.

**Comment by atiertant** [comment]
@f1ames 
doc say you could do it like this ...
https://github.com/ckeditor/ckeditor-docs/tree/master/guides/dev/features/colorbutton#custom-color-style-definition
so it's not clear or wrong ...

**Comment by f1ames** [comment]
The [`colorButton_foreStyle`](http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-colorButton_foreStyle) defines how color definition is stored which means what tag with what attribute will be used to apply color. The default value is

```
config.colorButton_foreStyle = {
	element: 'span',
	styles: { 'color': '#(color)' },
	overrides: [ {
		element: 'font', attributes: { 'color': null }
	} ]
};
```
so when you apply color via [Color Dialog](http://sdk.ckeditor.com/samples/colorbutton.html) it produces `<span style="color:#00ff00;">...</span>` markup.

If you define it like this

```
config.colorButton_foreStyle = {
	element: 'font',
	attributes: { 'color': '#FF0000' }
};
```
it will produce `<font color="#FF0000">...</font>` markup.

But it is only used to define what markup will be used to apply colors and have nothing to do with setting default text color.

**Comment by mlewand** [comment]
@atiertant As said before, please use either [our offical bug tracker](dev.ckeditor.com) or [ask question with CKEditor tag on StackOverflow](http://stackoverflow.com/questions/tagged/ckeditor) - that way others will be able to benefit from our answers.

**Comment by atiertant** [comment]
@mlewand i would love open a ticket at your bug tracker but i can't verify my email to register (your serveur don't send any email)

**Comment by atiertant** [comment]
@mlewand https://dev.ckeditor.com/ticket/14715 ;(
