### ISSUE TITLE
Integrating CKEditor guide - enhancements

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor-docs#7]
Missing topics:

1. Saving inline editor contents via AJAX.
2. Listening on changes (debouncing change event, checking dirty).
3. Autosaving.
4. Handling multiple editors.

**Comment by AnnaTomanek** [comment]
I consider this fiexd by http://docs.ckeditor.com/#!/guide/dev_savedata and updated http://docs.ckeditor.com/#!/guide/dev_framed + http://docs.ckeditor.com/#!/guide/dev_inline.
