### ISSUE TITLE
Broken links in guides/dev/tests/README.md

### ISSUE THREAD

**Issue by likemusic** [ckeditor/ckeditor-docs#70]
In section [Test Tools](https://github.com/ckeditor/ckeditor-docs/blob/master/guides/dev/tests/README.md#test-tools) invalid anchors links:
- [tools](https://github.com/benderjs/benderjs-ckeditor/blob/master/static/tools.js)
- [Editor Bot](https://github.com/benderjs/benderjs-ckeditor/blob/master/static/bot.js)

I can't fix it myself because in [actual benderjs repository](https://github.com/benderjs/benderjs) not exists files with the same path.

**Comment by f1ames** [comment]
@likemusic thank you for reporting. I created a PR fixing those links https://github.com/ckeditor/ckeditor-docs/pull/77. @AnnaTomanek if you could take a look and merged it if it is ok?
