### ISSUE TITLE
In Microsoft Edge the system stops me from entering a new line. I start a new line and it instantly deletes it

### ISSUE THREAD

**Issue by yubitib** [ckeditor/ckeditor-docs#80]
On the edit issue page I am seeing the following annoying behavior when using Microsoft Edge

I type text on the first line of the description and hit the Enter key. I can see the cursor jump to the next line and then instantly jump back. I can workaround the issue by typing a ":", but this is always put on a new line even when I do not want it to.

**Comment by f1ames** [comment]
Hello @yubitib,
could you add a link to the _edit issue page_ you mentioned? I am not entirely sure which one is that.

Thanks

**Comment by mlewand** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
