### ISSUE TITLE
Update information about widget styles.

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor-docs#82]
Since http://dev.ckeditor.com/ticket/13818 was resolved and included in 4.6.2 we can update information about styles exclusion for widgets (added in https://github.com/ckeditor/ckeditor-docs/commit/3fe64c0ccfb73bc9a44e90017ff913587c6a5261#diff-f0c1f8d1a24b70762bc9d893a9f579e4R108).

**Comment by f1ames** [comment]
PR created - #83.

**Comment by f1ames** [comment]
Updated `group` property description and code sample to cover single group and array of groups.

**Comment by mlewand** [comment]
I did an review on this, and applied some changes. It needs to be reviewed once again.

**Comment by Tade0** [comment]
Pushed some minor updates. Overall looks good.
