### ISSUE TITLE
Pasting content from Excel demo on SDK has a typo.

### ISSUE THREAD

**Issue by wojtekidd** [ckeditor/ckeditor-docs#91]
[Pasting content from Excel demo on SDK](http://sdk.ckeditor.com/samples/pastefromexcel.html) has a typo.
Should be _unaudited_.
![screen shot 2017-05-31 at 12 07 48](https://cloud.githubusercontent.com/assets/6146254/26627249/1847575c-45fa-11e7-80f6-7d29837412a3.png)

**Comment by mlewand** [comment]
This is an issue in sdk.
