### ISSUE TITLE
Add paste as plain text keystroke

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor-docs#93]
http://docs.ckeditor.com/#!/guide/dev_shortcuts page should include "Paste as Plain Text" command.

Remember that hotkey differs across platforms:

* Windows/Linux:
  * `ctrl + shift + v`, followed by `ctrl + v` for Edge.
  * `ctrl + shif + v` in all other cases.
* Mac:
  * `cmd + alt + shift + v` for Safari
  * `cmd + shift + v` in other cases? (needs confirmation doesn't have one to verify ATM)

**Comment by f1ames** [comment]
Moved to https://github.com/ckeditor/ckeditor-dev/issues/2909.
